<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'wp-whatsapp-chat-pro',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.0.20',
    ),
    'wp-dashboard-widget-news' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-dashboard-widget-news',
      'ver' => '1.0.9',
    ),
    'wp-license-client' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-license-client',
      'ver' => '1.7.9',
    ),
    'wp-notice-plugin-required' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-notice-plugin-required',
      'ver' => '2.0.7',
    ),
    'wp-plugin-table-links' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-plugin-table-links',
      'ver' => '1.0.8',
    ),
  ),
);
