<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'QuadLayers\\WP_Plugin_Table_Links\\' => array($baseDir . '/jetpack_vendor/quadlayers/wp-plugin-table-links/src'),
    'QuadLayers\\WP_Notice_Plugin_Required\\' => array($baseDir . '/jetpack_vendor/quadlayers/wp-notice-plugin-required/src'),
    'QuadLayers\\WP_License_Client\\' => array($baseDir . '/jetpack_vendor/quadlayers/wp-license-client/src'),
    'QuadLayers\\WP_Dashboard_Widget_News\\' => array($baseDir . '/jetpack_vendor/quadlayers/wp-dashboard-widget-news/src'),
    'QuadLayers\\PluginFeedback\\' => array($vendorDir . '/franmastromarino/wp-plugin-feedback/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
