<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '3773ef3f09c37da5478d578e32b03a4b' => $baseDir . '/jetpack_vendor/automattic/jetpack-assets/actions.php',
    'ee9922e131abffdaa2e5fa31e355dc22' => $baseDir . '/jetpack_vendor/quadlayers/wp-license-client/src/helpers.php',
    '2844defb5028a78da2d95bab6a7aa33d' => $baseDir . '/compatibility/license.php',
);
