<?php return array(
    'root' => array(
        'name' => 'quadlayers/wp-whatsapp-chat-pro',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'cd2ef79cf479ed0b16a21365d6b45feedf198725',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'automattic/jetpack-assets' => array(
            'pretty_version' => 'v4.0.20',
            'version' => '4.0.20.0',
            'reference' => '45bb895c065ff680585664d5a2ea2862cac5a2ac',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/automattic/jetpack-assets',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'automattic/jetpack-composer-plugin' => array(
            'pretty_version' => 'v4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'e0a5ad3a32802ec156cb38c6280e2c12bfc63ffe',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../automattic/jetpack-composer-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'automattic/jetpack-constants' => array(
            'pretty_version' => 'v3.0.8',
            'version' => '3.0.8.0',
            'reference' => 'f9bf00ab48956b8326209e7c0baf247a0ed721c4',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/automattic/jetpack-constants',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'automattic/jetpack-status' => array(
            'pretty_version' => 'v5.1.4',
            'version' => '5.1.4.0',
            'reference' => 'b49e496454fef31b15684d80aaea939802f79653',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/automattic/jetpack-status',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'franmastromarino/wp-plugin-feedback' => array(
            'pretty_version' => 'v1.0.8',
            'version' => '1.0.8.0',
            'reference' => 'f6f2f175a6ad5ad2043748985061cb6591ce17ec',
            'type' => 'project',
            'install_path' => __DIR__ . '/../franmastromarino/wp-plugin-feedback',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => '5cf826f2991858b54d5c3809bee745560a1042a7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
            ),
        ),
        'quadlayers/wp-dashboard-widget-news' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'reference' => 'c8f270a3de46f986dab8b9547848dc6b6f0ae7fe',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/quadlayers/wp-dashboard-widget-news',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'quadlayers/wp-license-client' => array(
            'pretty_version' => '1.7.9',
            'version' => '1.7.9.0',
            'reference' => '645750af610fa81eafc227d912c4d385fe28ddf7',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/quadlayers/wp-license-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'quadlayers/wp-notice-plugin-required' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'reference' => 'fd3d10dbdb39be738c3ef320e43cb7cd4e59e071',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/quadlayers/wp-notice-plugin-required',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'quadlayers/wp-plugin-table-links' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '22bd6b20b40c7878c966eb57f45b1d9046728d6b',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../../jetpack_vendor/quadlayers/wp-plugin-table-links',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'quadlayers/wp-whatsapp-chat-pro' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'cd2ef79cf479ed0b16a21365d6b45feedf198725',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
